### ISSUE TITLE
[ci] Show failed tests as failed

### ISSUE THREAD

**Issue by simitt** [elastic/ecs-logging-go-zap#13]
The test pipeline stage `./ci/script/run-tests.sh` is shown as `success` even if tests fail, only the stage to archive JUnit formttet test results fails. 

<img width="582" alt="Screenshot 2020-04-24 at 10 40 03" src="https://user-images.githubusercontent.com/5555349/80192884-29fcec80-8618-11ea-90b7-309c796bb851.png">

<img width="1836" alt="Screenshot 2020-04-24 at 10 40 15" src="https://user-images.githubusercontent.com/5555349/80192875-25d0cf00-8618-11ea-886d-dcf734db1caf.png">

The test stage itself should be marked as failed.

**Comment by simitt** [comment]
@elastic/observablt-robots it would be great if someone could take a look at this.

**Comment by kuisathaverat** [comment]
if the script that runs the tests returns exit code 0 the step will be a success, however, if there are failed tests the junit step will mark the build as UNSTABLE, I guess you want to mark the job as FAILED if a test failed, isn't it?

**Comment by simitt** [comment]
>I guess you want to mark the job as FAILED if a test failed, isn't it?

yes
