### ISSUE TITLE
Make ecszap.WrapCore available as a zap.Option

### ISSUE THREAD

**Issue by segevfiner** [elastic/ecs-logging-go-zap#15]
This package currently recommends using the lower level less convenient zapcore way of initializing zap, you can use the higher level init by just doing this:
```go
config := zap.NewProductionConfig()
config.EncoderConfig = ecszap.NewDefaultEncoderConfig().ToZapCoreEncoderConfig()

logger, err := config.Build(
	zap.WrapCore(func(core zapcore.Core) zapcore.Core {
		return ecszap.WrapCore(core)
	}),
)
```

If you make `ecszap.WrapCore` a `zap.Option` or add a new function which is a `zap.Option` wrapping it, then this is shortened to:
```go
config := zap.NewProductionConfig()
config.EncoderConfig = ecszap.NewDefaultEncoderConfig().ToZapCoreEncoderConfig()

logger, err := config.Build(ecszap.WrapCore())
```

**Comment by axw** [comment]
@segevfiner sorry it took so long to respond!

It's not possible to implement `zap.Option` directly, but we could make a function that returns a `zap.Option` which does what you describe. Another option, similar to your first example, is to pass `ecszap.WrapCore` directly to `zap.WrapCore`:

```go
logger, err := config.Build(zap.WrapCore(ecszap.WrapCore))
```

I think it's useful to have a function to wrap a Core directly (e.g. for use with the underlying zapcore package), but we could add another function like

```go
package ecszap

// WrapCoreOption returns a zap.Option 
func WrapCoreOption() zap.Option {
    return zap.WrapCore(WrapCore)
}
```

@simitt WDYT?

**Comment by simitt** [comment]
Thanks for the suggestions @segevfiner and @axw and apologies I didn't come back to this earlier. There is a PR up for review  https://github.com/elastic/ecs-logging-go-zap/pull/22.
