### ISSUE TITLE
Document configuration (EncoderConfig.EncodeLevel, etc.)

### ISSUE THREAD

**Issue by dohq** [elastic/ecs-logging-go-zap#35]
Document how to configure `log.level`, to align with other ECS loggers such as log4j2-ecs-layout.

Original description:

<hr/>

I followed the official documentation and configured the go app.
Then I noticed that the log level was in lower case.
If you use log4j2-ecs-layout, you don't need to set anything in particular to get uppercase.
This creates confusion, mainly in log visualization.

If there is a way to set it up, it would be nice to have it reflected in the documentation.
or It would also be nice if the default were changed to uppercase.

**Comment by axw** [comment]
@dohq as we already released v1.0.0, I think it's too late to change the default. That would break terms aggregations on `log.level`, which performs an exact match.

It is possible to customise the `log.level` encoding. See this test: https://github.com/elastic/ecs-logging-go-zap/blob/040de20035bec8c397a3b5623e15a85b78051238/encoder_config_test.go#L133-L149

> If there is a way to set it up, it would be nice to have it reflected in the documentation.

:+1: I'll update the issue title, so this is about updating the docs.
