### ISSUE TITLE
Make timestamp encoding configurable

### ISSUE THREAD

**Issue by simitt** [elastic/ecs-logging-go-zap#9]
Currently `@timestamp` is set to microseconds. Since the format is not defined by ECS, ensure this can be configured.

**Comment by segevfiner** [comment]
ECS defines time as the `date` (And not the newer `date_microseconds`) and mapped as such by beats, which means it needs to be in milliseconds. The example in the ECS docs shows it using the ISO string format.

P.S. Microseconds timestamps would be nicer of course, but don't have an official provision in the ECS spec, there also doesn't seem to be an official provision for tie-breaking (One that is also configured by default in ES Nd beats) when multiple record with the same timestamp are queried. Might need to open separete issues about this agains't ECS if there aren't already.

**Comment by simitt** [comment]
In https://github.com/elastic/ecs-logging-go-zap/pull/23/commits/b0f829d194facca0b11f51823ebadcb47eff441d I am attempting to remove the option to configure the timestamp and instead always set it to the `ISO8601`. This is in alignment with other ecs-logger libraries (e.g. java, python, go-logrus).

Beats sets the time encoding to [`zapcore.ISO8601TimeEncoder`](https://github.com/elastic/beats/blob/master/libbeat/logp/encoding.go#L35), therefore this should not be a problem with beats.

**Comment by simitt** [comment]
Since I haven't hear anything back, closing this issue out - let me know if there are any concerns and we can re-evaluate.

**Comment by jaxonly** [comment]
Currently, ElasticSearch supports timestamp at the nanosecond level. As Go is currently very fast, it is easy to encounter disorder caused by timestamps only supporting milliseconds. Should we consider separating them into configurable options?
